// Code generated by MockGen. DO NOT EDIT.
// Source: website.go

// Package fetcher is a generated GoMock package.
package fetcher

import (
	context "context"
	reflect "reflect"

	goquery "github.com/PuerkitoBio/goquery"
	gomock "github.com/golang/mock/gomock"
)

// MockWebsiteFetcher is a mock of WebsiteFetcher interface.
type MockWebsiteFetcher struct {
	ctrl     *gomock.Controller
	recorder *MockWebsiteFetcherMockRecorder
}

// MockWebsiteFetcherMockRecorder is the mock recorder for MockWebsiteFetcher.
type MockWebsiteFetcherMockRecorder struct {
	mock *MockWebsiteFetcher
}

// NewMockWebsiteFetcher creates a new mock instance.
func NewMockWebsiteFetcher(ctrl *gomock.Controller) *MockWebsiteFetcher {
	mock := &MockWebsiteFetcher{ctrl: ctrl}
	mock.recorder = &MockWebsiteFetcherMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockWebsiteFetcher) EXPECT() *MockWebsiteFetcherMockRecorder {
	return m.recorder
}

// Fetch mocks base method.
func (m *MockWebsiteFetcher) Fetch(ctx context.Context, URL string) (*goquery.Document, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Fetch", ctx, URL)
	ret0, _ := ret[0].(*goquery.Document)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Fetch indicates an expected call of Fetch.
func (mr *MockWebsiteFetcherMockRecorder) Fetch(ctx, URL interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Fetch", reflect.TypeOf((*MockWebsiteFetcher)(nil).Fetch), ctx, URL)
}
